name: Pull Request

on:
  pull_request:
    branches:
      - main
      - alpha
    paths-ignore:
      - 'docs/**'
      - 'scripts/**'

permissions:
  contents: read

jobs:
  build:
    name: 'Build @algorandfoundation/algorand-typescript-testing'
    uses: algorandfoundation/algokit-shared-config/.github/workflows/node-ci.yml@main
    with:
      run-commit-lint: true
      run-build: true
      install-algokit: true
      install-puyapy: true
      audit-script: npm run audit
