name: Pull Request

on:
  pull_request:
    branches:
      - main
      - alpha
    paths-ignore:
      - 'docs/**'
      - 'scripts/**'

permissions:
  contents: read

jobs:
  build:
    name: 'Build @algorandfoundation/algorand-typescript-testing'
    uses: ./.github/workflows/node-ci.yml
    with:
      pre-test-script: |
        pipx install algokit --python 3.12.6
        algokit localnet reset --update
        pipx install puyapy --python 3.12.6
      node-version: 20.x
      run-build: true
      run-commit-lint: true
      audit-script: npm run audit
